-- ============================================================
-- SMART CONSTRUCTION SITE
-- Database Schema
-- Backend: Supabase PostgreSQL
-- ============================================================


-- ============================================================
-- 1. PROJECTS TABLE
-- ============================================================

CREATE TABLE projects (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name text NOT NULL,
    location text,
    start_date date,
    overall_progress integer DEFAULT 0
);


-- ============================================================
-- 2. ACTIVITIES TABLE
-- ============================================================

CREATE TABLE activities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint REFERENCES projects(id) ON DELETE CASCADE,
    activity_name text NOT NULL,
    progress integer DEFAULT 0,
    status text,
    activity_date date,
    remarks text,
    created_at timestamp with time zone DEFAULT now(),
    location text,
    workers_count integer DEFAULT 0
);


-- ============================================================
-- 3. WORKERS TABLE
-- ============================================================

CREATE TABLE workers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    role text,
    department text,
    status text
);


-- ============================================================
-- 4. EQUIPMENT TABLE
-- ============================================================

CREATE TABLE equipment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_name text NOT NULL,
    equipment_type text,
    status text,
    location text,
    next_maintenance date
);


-- ============================================================
-- 5. SAFETY ISSUES TABLE
-- ============================================================

CREATE TABLE safety_issues (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue text NOT NULL,
    location text,
    severity text,
    status text,
    reported_by text,
    reported_date date,
    remarks text
);


-- ============================================================
-- SAMPLE PROJECT DATA
-- ============================================================

INSERT INTO projects
(project_name, location, start_date, overall_progress)
VALUES
('Smart Construction Site', 'Chennai', '2026-09-07', 70);


-- ============================================================
-- SAMPLE ACTIVITY DATA
-- ============================================================

INSERT INTO activities
(project_id, activity_name, progress, status, activity_date, location, workers_count, remarks)
VALUES
(3, 'Foundation', 100, 'Completed', '2026-09-07',
 'Block A - Ground Floor', 0,
 'Foundation work completed.'),

(3, 'Structure', 70, 'In Progress', '2026-09-07',
 'Block A', 0,
 'Structural work is in progress.'),

(3, 'Electrical Work', 40, 'In Progress', '2026-09-07',
 'Block B', 0,
 'Electrical work is in progress.'),

(3, 'Concrete Pouring', 85, 'In Progress', '2026-09-08',
 'Block A - Ground Floor', 0,
 'Concrete pouring is in progress.'),

(3, 'Brickwork', 60, 'In Progress', '2026-09-08',
 'Block A - First Floor', 10,
 'Brickwork is in progress.'),

(3, 'Electrical Installation', 40, 'In Progress', '2026-09-08',
 'Block B - Ground Floor', 6,
 'Electrical conduit installation is underway.');


-- ============================================================
-- SAMPLE WORKFORCE DATA
-- ============================================================

INSERT INTO workers
(name, role, department, status)
VALUES
('Arun Kumar', 'Site Engineer', 'Civil', 'Active'),
('Suresh', 'Mason', 'Civil', 'Active'),
('Ravi', 'Electrician', 'Electrical', 'Active'),
('Manoj', 'Safety Supervisor', 'Safety', 'Active'),
('Karthik', 'Helper', 'Civil', 'Active');


-- ============================================================
-- SAMPLE EQUIPMENT DATA
-- ============================================================

INSERT INTO equipment
(equipment_name, equipment_type, status, location, next_maintenance)
VALUES
('Tower Crane 01', 'Tower Crane', 'Operational',
 'Block A - Main Site', '2026-09-25'),

('Concrete Mixer 01', 'Concrete Mixer', 'Operational',
 'Block A - Ground Floor', '2026-09-20'),

('Excavator 01', 'Excavator', 'Under Maintenance',
 'Block B - Excavation Area', '2026-09-10'),

('Generator 01', 'Generator', 'Operational',
 'Main Site', '2026-09-30');


-- ============================================================
-- SAMPLE SAFETY ISSUE DATA
-- ============================================================

INSERT INTO safety_issues
(issue, location, severity, status, reported_by, reported_date, remarks)
VALUES
('Improper electrical cable placement',
 'Block B - Ground Floor',
 'Medium',
 'Open',
 'Safety Officer',
 '2026-09-08',
 'Electrical cables need to be properly secured.'),

('Worker without helmet',
 'Block A - Floor 2',
 'High',
 'Open',
 'Safety Officer',
 '2026-09-08',
 'Worker was observed without a safety helmet.'),

('Safety signage missing',
 'Main Entrance',
 'Low',
 'Resolved',
 'Safety Officer',
 '2026-09-08',
 'Required safety signage was installed.');
